feat(github): trying to fix broken azure deploy

diff --git a/terraform/website/bin/azure-website-sync b/terraform/website/bin/azure-website-sync
--- a/terraform/website/bin/azure-website-sync
+++ b/terraform/website/bin/azure-website-sync
@@ -5,6 +5,8 @@ set -xe
 QUERY=`echo $(</dev/stdin)`
 FOLDER=`echo $QUERY | jq -r .folder`
 TENANT_ID=`echo $QUERY | jq -r .tenant_id`
+AZURE_RESOURCE_GROUP=`echo $QUERY | jq -r .resource_group`
+AZURE_CDN_ENDPOINT=`echo $QUERY | jq -r .cdn_endpoint`
 STORAGE_CONTAINER_URL=`echo $QUERY | jq -r .storage_container_url`
 
 AZURE_AZCOPY_LOGIN_OUTPUT=`azcopy login --tenant-id ${TENANT_ID}`
@@ -24,14 +26,14 @@ if [[ "${AZURE_STORAGE_SYNCHRONIZATION_EXIT_CODE}" != "0" ]] ; then
   exit 1
 fi
 
-#if [[ "${S3_SYNCHRONIZATION_OUTPUT}" != "" ]] ; then
-#  CLOUDFRONT_INVALIDATION_CACHE_OUTPUT=`aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*" --profile ${PROFILE}`
-#  CLOUDFRONT_INVALIDATION_CACHE_EXIT_CODE=$?
-#
-#  if [[ "${CLOUDFRONT_INVALIDATION_CACHE_EXIT_CODE}" != "0" ]] ; then
-#    echo "{\"error\": \"${CLOUDFRONT_INVALIDATION_EXIT_CODE}\", \"reason\": \"${CLOUDFRONT_INVALIDATION_CACHE_OUTPUT}\"}"
-#  fi
-#fi
+if [[ "${S3_SYNCHRONIZATION_OUTPUT}" != "" ]] ; then
+  CLOUDFRONT_INVALIDATION_CACHE_OUTPUT=`az cdn endpoint purge -g ${AZURE_RESOURCE_GROUP} -n ${AZURE_CDN_ENDPOINT} --content-paths '/*'`
+  CLOUDFRONT_INVALIDATION_CACHE_EXIT_CODE=$?
+
+  if [[ "${CLOUDFRONT_INVALIDATION_CACHE_EXIT_CODE}" != "0" ]] ; then
+    echo "{\"error\": \"${CLOUDFRONT_INVALIDATION_EXIT_CODE}\", \"reason\": \"${CLOUDFRONT_INVALIDATION_CACHE_OUTPUT}\"}"
+  fi
+fi
 
 echo '{"result":"ok"}'
 
